Q1. What is the distinction between a numpy array and a pandas data frame? Is there a way to
    convert between the two if there is?
   
Numpy:

    1. The powerful tool of numpy is Arrays.
    2. Indexing of numpy Arrays is very fast.
    3. It has provides a lot of convenient and optimized methods for performing several mathematical operations on vectors.
    
Pandas:

    1. The powerful tools of pandas are Data frame and Series.
    2. Indexing of the pandas series is very slow as compared to numpy arrays.
    3. it can be seen as a spreadsheet having rows and columns.
conversion:
    Dataframe=pandas.DataFrame(array)

In [1]:
import pandas as pd 
import numpy as np

In [4]:
# array in numpy 
arr = np.array([[23, 46, 85],
                [43, 56, 99],
                [11, 34, 55]])


In [3]:
print(arr)

[[23 46 85]
 [43 56 99]
 [11 34 55]]


In [6]:
# converting numpy array into pandas data frame:
Dataframe=pd.DataFrame(arr)

In [7]:
Dataframe

0   1   2
0  23  46  85
1  43  56  99
2  11  34  55

Q2. Identify some of the plotting techniques that are used to produce a stock-market chart ?

Ans: Bar chart, Line Chart are used for plotting.


Q3. Why is it essential to print a legend on a stock market chart?

Legend will help comparison between different stocks, so will be essential on a stock market chart

Q4. What is the best way to limit the length of a pandas data frame to less than a year ?

We can use start and end parameters for that. In start we write the date from where we are starting and at the end we write the end date. SO within this span we can restric the duration.Also we can use the parameters like periods for how much times we need the duration and we can also use the frequency parameter.


# Q5. What is the definition of a 180-day moving average ?

Ans: : The 180-day moving average is represented as a line on charts and represents the average price over the past 180 days. The moving average can give traders a sense regarding whether the trend is up or down, while also identifying potential support or resistance areas.

6. What is the definition of a 180-day moving average?

A 180-day moving average is a type of technical indicator used in financial analysis that calculates the average price of a security over the past 180 trading days. The moving average is recalculated continuously over time, providing a smoothed trend line of the security's price performance. The 180-day moving average is often used as a long-term trend indicator, helping analysts to identify major price trends and potential reversals.

7. Did the chapter&#39;s final example use &quot;indirect&quot; importing? If so, how exactly do you do it?

Yes, the chapter's final example uses "indirect" importing. Indirect importing is achieved by creating an empty `__init__.py` file in the directory that you want to import from, and then importing the desired module(s) in that `__init__.py` file using relative imports.

For example, if you have the following directory structure:

```
my_package/
    __init__.py
    module_a.py
    module_b.py
    subdir/
        __init__.py
        module_c.py
```

To import `module_c` from `module_a`, you would need to add the following import statement to `my_package/subdir/__init__.py`:

```python
from ..module_b import some_function
```

Then in `module_a`, you can import `some_function` from `module_c` like this:

```python
from my_package.subdir import some_function
``` 

This way, you can import the desired module(s) directly from the package, without having to import them individually from their respective subdirectories.